name: Check
on: push

jobs:
  link:
    name: Ruff lint and format
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cached-python

      - run: inv lint

  type_check:
    name: Static type checks
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cached-python

      - run: inv protoc

      - name: Build type stubs
        run: inv type-stubs

      - run: inv type-check

  check-copyright:
    name: Check copyright
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cached-python

      - run: inv check-copyright

  doc-test:
    name: Doc generation
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cached-python

      - name: Build protobuf
        run: inv protoc

      # Makes sure doc generation doesn't break on client imports etc.
      - name: Generate reference docs
        run: python -m modal_docs.gen_reference_docs reference_docs_output

      - name: Generate CLI docs
        run: python -m modal_docs.gen_cli_docs cli_docs
